/**
 * 补充的存储驱动配置：仓库里有实现、但前端「新增存储」下拉里选不到的驱动都在这里。
 *
 * 为什么需要这个文件：`/admin/driver/list` 返回的对象的**键**就是下拉项 ——
 * 前端 AddOrEdit.tsx 用 `Object.keys(drivers())` 渲染、Item.tsx 再按
 * `drivers.<键名>.<字段名>` 取标签（官方前端源码里的写法，没有第二处来源）。
 * 所以键名必须与语言包里的驱动命名空间一致，否则整页字段只剩自动推断的英文。
 *
 * 字段依据（不要凭印象改）：
 *   · 字段名与类型 = 本仓库 drivers/<目录>/types.ts 里 Addition 的声明，
 *     也就是驱动真正读取的字段；多写一个没实现的字段，界面上就是空旋钮
 *   · 类型 / 选项 / 默认值 / 必填 = 上游 Go 版 OpenList 的 drivers/<目录>/meta.go
 *
 * 与 admin.ts 里那份的关系：`/admin/driver/list` 会把两者合并后下发，
 * 键冲突时以本文件为准（见 admin.ts 的 Object.assign）。
 */

export const COMMON_FIELDS = [
  {
    name: "mount_path",
    type: "string",
    default: "",
    required: true,
  },
  {
    name: "order",
    type: "number",
    default: "0",
    required: false,
  },
  {
    name: "remark",
    type: "string",
    default: "",
    required: false,
  },
  {
    name: "cache_expiration",
    type: "number",
    default: "30",
    required: false,
  },
  {
    name: "web_proxy",
    type: "bool",
    default: "false",
    required: false,
  },
  {
    name: "webdav_policy",
    type: "select",
    options: "302_redirect,use_proxy_url,native_proxy",
    default: "302_redirect",
    required: false,
  },
  {
    name: "down_proxy_url",
    type: "string",
    default: "",
    required: false,
  },
  {
    name: "seed_policy",
    type: "select",
    options: "inherit,on,off",
    default: "inherit",
    required: true,
    help: "Override automatic transfer-seed generation for this storage",
  },
]

export const EXTRA_DRIVER_CONFIGS: Record<string, any> = {
  "123 Open": {
    name: "123 Open",
    default_mount_path: "/123open",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "client_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "client_secret",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "access_token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "use_online_api",
        type: "bool",
        default: "true",
        required: false,
      },
      {
        name: "api_url_address",
        type: "string",
        default: "https://api.oplist.org/123cloud/renewapi",
        required: false,
      },
      {
        name: "root_folder_id",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "123 Open",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "0",
    },
  },
  "189CloudTV": {
    name: "189CloudTV",
    default_mount_path: "/189tv",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "access_token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "root_folder_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "order_by",
        type: "select",
        options: "filename,filesize,lastOpTime",
        default: "filename",
        required: false,
      },
      {
        name: "order_direction",
        type: "select",
        options: "asc,desc",
        default: "asc",
        required: false,
      },
      {
        name: "type",
        type: "select",
        options: "family,personal",
        default: "personal",
        required: false,
      },
      {
        name: "family_id",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "189CloudTV",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "-11",
    },
  },
  "189CloudPC": {
    name: "189CloudPC",
    default_mount_path: "/189pc",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "username",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "password",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "root_folder_id",
        type: "string",
        default: "-11",
        required: false,
      },
      {
        name: "captcha_mode",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "device_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "session_key",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "session_secret",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "login_type",
        type: "select",
        options: "password,qrcode",
        default: "password",
        required: true,
      },
    ],
    config: {
      name: "189CloudPC",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "-11",
    },
  },
  "BaiduPhoto": {
    name: "BaiduPhoto",
    default_mount_path: "/baiduphoto",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "cookie",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "show_type",
        type: "select",
        options: "root,root_only_album,root_only_file",
        default: "root",
        required: false,
      },
      {
        name: "album_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "delete_origin",
        type: "bool",
        default: "false",
        required: false,
      },
      {
        name: "upload_thread",
        type: "string",
        default: "3",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "BaiduPhoto",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "ChaoXingGroupDrive": {
    name: "ChaoXingGroupDrive",
    default_mount_path: "/chaoxing",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "user_name",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "password",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "bbsid",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "root_folder_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "cookie",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "ChaoXingGroupDrive",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "Chunk": {
    name: "Chunk",
    default_mount_path: "/chunk",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "remote_path",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "part_size",
        type: "number",
        default: "0",
        required: true,
        help: "true",
      },
      {
        name: "chunk_large_file_only",
        type: "bool",
        default: "false",
        required: false,
        help: "true",
      },
      {
        name: "chunk_prefix",
        type: "string",
        default: "[openlist_chunk]",
        required: false,
        help: "true",
      },
      {
        name: "custom_ext",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "store_hash",
        type: "bool",
        default: "true",
        required: false,
      },
      {
        name: "num_list_workers",
        type: "number",
        default: "5",
        required: true,
      },
      {
        name: "thumbnail",
        type: "bool",
        default: "false",
        required: true,
        help: "true",
      },
      {
        name: "show_hidden",
        type: "bool",
        default: "true",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "Chunk",
      local_sort: true,
      only_local: false,
      only_proxy: true,
      no_cache: true,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "Cloudreve": {
    name: "Cloudreve",
    default_mount_path: "/cloudrevev3",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "address",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "username",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "password",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "cookie",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "custom_ua",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "enable_thumb_and_folder_size",
        type: "bool",
        default: "false",
        required: false,
      },
    ],
    config: {
      name: "Cloudreve",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "Cloudreve V4": {
    name: "Cloudreve V4",
    default_mount_path: "/cloudrevev4",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "address",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "username",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "password",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "access_token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "custom_ua",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "enable_thumb",
        type: "bool",
        default: "false",
        required: false,
      },
      {
        name: "order_by",
        type: "select",
        options: "created_at,name,size,updated_at",
        default: "name",
        required: true,
      },
      {
        name: "order_direction",
        type: "select",
        options: "asc,desc",
        default: "asc",
        required: true,
      },
    ],
    config: {
      name: "Cloudreve V4",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "cloudreve://my",
    },
  },
  "CNB Releases": {
    name: "CNB Releases",
    default_mount_path: "/cnbreleases",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "repo",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "token",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "use_tag_name",
        type: "bool",
        default: "false",
        required: false,
        help: "true",
      },
      {
        name: "default_branch",
        type: "string",
        default: "main",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "CNB Releases",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "Degoo": {
    name: "Degoo",
    default_mount_path: "/degoo",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "root_folder_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "username",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
      {
        name: "password",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
      {
        name: "access_token",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "Degoo",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "0",
    },
  },
  "Doubao": {
    name: "Doubao",
    default_mount_path: "/doubao",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "cookie",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "download_api",
        type: "select",
        options: "get_file_url,get_download_info",
        default: "get_file_url",
        required: false,
      },
      {
        name: "limit_rate",
        type: "number",
        default: "0",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "Doubao",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "0",
    },
  },
  "FebBox": {
    name: "FebBox",
    default_mount_path: "/febbox",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "root_folder_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "client_id",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "client_secret",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "sort_rule",
        type: "select",
        options: "ext_asc,ext_desc,name_asc,name_desc,size_asc,size_desc,update_asc,update_desc",
        default: "name_asc",
        required: true,
      },
      {
        name: "page_size",
        type: "number",
        default: "100",
        required: true,
        help: "true",
      },
      {
        name: "user_ip",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "FebBox",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: true,
      need_ms: false,
      default_root: "0",
    },
  },
  "GitHub Releases": {
    name: "GitHub Releases",
    default_mount_path: "/githubreleases",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "repo_structure",
        type: "string",
        default: "OpenListTeam/OpenList",
        required: false,
        help: "true",
      },
      {
        name: "show_readme",
        type: "bool",
        default: "true",
        required: false,
        help: "true",
      },
      {
        name: "token",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
      {
        name: "show_source_code",
        type: "bool",
        default: "false",
        required: false,
        help: "true",
      },
      {
        name: "show_all_version",
        type: "bool",
        default: "false",
        required: false,
        help: "true",
      },
      {
        name: "gh_proxy",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "GitHub Releases",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: true,
      need_ms: false,
      default_root: "/",
    },
  },
  "GooglePhoto": {
    name: "GooglePhoto",
    default_mount_path: "/googlephoto",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "root_folder_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "client_id",
        type: "string",
        default: "202264815644.apps.googleusercontent.com",
        required: false,
      },
      {
        name: "client_secret",
        type: "string",
        default: "X4Z3ca8xfWDb1Voo-F9a7ZxJ",
        required: false,
      },
      {
        name: "show_archive",
        type: "bool",
        default: "false",
        required: false,
      },
    ],
    config: {
      name: "GooglePhoto",
      local_sort: true,
      only_local: false,
      only_proxy: true,
      no_cache: false,
      no_upload: true,
      need_ms: false,
      default_root: "root",
    },
  },
  "HalalCloudOpen": {
    name: "HalalCloudOpen",
    default_mount_path: "/halalcloudopen",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "client_id",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "client_secret",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
      {
        name: "host",
        type: "string",
        default: "openapi.2dland.cn",
        required: false,
      },
      {
        name: "root_folder_id",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "HalalCloudOpen",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "IPFS API": {
    name: "IPFS API",
    default_mount_path: "/ipfsapi",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "mode",
        type: "select",
        options: "ipfs,ipns,mfs",
        default: "ipfs",
        required: true,
      },
      {
        name: "endpoint",
        type: "string",
        default: "http://127.0.0.1:5001",
        required: false,
      },
      {
        name: "gateway",
        type: "string",
        default: "http://127.0.0.1:8080",
        required: false,
      },
      {
        name: "root_path",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "IPFS API",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "KodBox": {
    name: "KodBox",
    default_mount_path: "/kodbox",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "address",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "username",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "password",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "root_path",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "KodBox",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "LenovoNasShare": {
    name: "LenovoNasShare",
    default_mount_path: "/lenovonasshare",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "share_id",
        type: "string",
        default: "",
        required: true,
        help: "true",
      },
      {
        name: "share_pwd",
        type: "string",
        default: "",
        required: true,
        help: "true",
      },
      {
        name: "host",
        type: "string",
        default: "https://siot-share.lenovo.com.cn",
        required: false,
        help: "true",
      },
      {
        name: "show_root_folder",
        type: "bool",
        default: "true",
        required: false,
      },
      {
        name: "root_path",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "LenovoNasShare",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: true,
      need_ms: false,
      default_root: "/",
    },
  },
  "MediaFire": {
    name: "MediaFire",
    default_mount_path: "/mediafire",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "cookie",
        type: "string",
        default: "",
        required: true,
        help: "true",
      },
      {
        name: "session_token",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
      {
        name: "chunk_size",
        type: "number",
        default: "100",
        required: false,
      },
      {
        name: "order_by",
        type: "select",
        options: "name,size,time",
        default: "name",
        required: false,
      },
      {
        name: "order_direction",
        type: "select",
        options: "asc,desc",
        default: "asc",
        required: false,
      },
    ],
    config: {
      name: "MediaFire",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "Misskey": {
    name: "Misskey",
    default_mount_path: "/misskey",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "endpoint",
        type: "string",
        default: "https://misskey.io",
        required: false,
      },
      {
        name: "access_token",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "root_path",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "Misskey",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "MoPan": {
    name: "MoPan",
    default_mount_path: "/mopan",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "phone",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "password",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "sms_code",
        type: "string",
        default: "",
        required: false,
        help: "true",
      },
      {
        name: "root_folder_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "cloud_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "order_by",
        type: "select",
        options: "filename,filesize,lastOpTime",
        default: "filename",
        required: false,
      },
      {
        name: "order_direction",
        type: "select",
        options: "asc,desc",
        default: "asc",
        required: false,
      },
      {
        name: "device_info",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "upload_thread",
        type: "string",
        default: "3",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "MoPan",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
      alert: "info",
    },
  },
  "NeteaseMusic": {
    name: "NeteaseMusic",
    default_mount_path: "/neteasemusic",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "cookie",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "song_limit",
        type: "number",
        default: "200",
        required: false,
        help: "true",
      },
    ],
    config: {
      name: "NeteaseMusic",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "OpenList": {
    name: "OpenList",
    default_mount_path: "/openlist",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "url",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "username",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "password",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "meta_password",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "root_path",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "OpenList",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "OpenListShare": {
    name: "OpenListShare",
    default_mount_path: "/openlistshare",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "url",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "sid",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "pwd",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "forward_archive_requests",
        type: "bool",
        default: "true",
        required: false,
      },
    ],
    config: {
      name: "OpenListShare",
      local_sort: true,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: true,
      need_ms: false,
      default_root: "/",
    },
  },
  "QuarkOpen": {
    name: "QuarkOpen",
    default_mount_path: "/quarkopen",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "access_token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "app_id",
        type: "string",
        default: "",
        required: true,
        help: "true",
      },
      {
        name: "sign_key",
        type: "string",
        default: "",
        required: true,
        help: "true",
      },
      {
        name: "api_url_address",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "use_online_api",
        type: "bool",
        default: "false",
        required: false,
      },
      {
        name: "order_by",
        type: "select",
        options: "created_at,file_name,file_type,none,updated_at",
        default: "created_at",
        required: false,
      },
      {
        name: "order_direction",
        type: "select",
        options: "asc,desc",
        default: "asc",
        required: false,
      },
    ],
    config: {
      name: "QuarkOpen",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "QuarkTV": {
    name: "QuarkTV",
    default_mount_path: "/quarkuctv",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "device_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "order_by",
        type: "select",
        options: "file_name,updated_at",
        default: "file_name",
        required: false,
      },
      {
        name: "order_direction",
        type: "select",
        options: "asc,desc",
        default: "desc",
        required: false,
      },
      {
        name: "link_method",
        type: "select",
        options: "download,streaming",
        default: "download",
        required: true,
      },
      {
        name: "variant",
        type: "select",
        options: "quark,uc",
        default: "quark",
        required: false,
      },
    ],
    config: {
      name: "QuarkTV",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "Teambition": {
    name: "Teambition",
    default_mount_path: "/teambition",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "region",
        type: "select",
        options: "china,international",
        default: "china",
        required: true,
      },
      {
        name: "cookie",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "project_id",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "order_by",
        type: "select",
        options: "created,fileName,fileSize,updated",
        default: "fileName",
        required: false,
      },
      {
        name: "order_direction",
        type: "select",
        options: "Asc,Desc",
        default: "Asc",
        required: false,
      },
    ],
    config: {
      name: "Teambition",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "Teldrive": {
    name: "Teldrive",
    default_mount_path: "/teldrive",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "url",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "access_token",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "root_path",
        type: "string",
        default: "",
        required: false,
      },
    ],
    config: {
      name: "Teldrive",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
  "UCTV": {
    name: "UCTV",
    default_mount_path: "/uctv",
    common: COMMON_FIELDS,
    additional: [
      {
        name: "refresh_token",
        type: "string",
        default: "",
        required: true,
      },
      {
        name: "device_id",
        type: "string",
        default: "",
        required: false,
      },
      {
        name: "order_by",
        type: "select",
        options: "file_name,updated_at",
        default: "file_name",
        required: false,
      },
      {
        name: "order_direction",
        type: "select",
        options: "asc,desc",
        default: "asc",
        required: false,
      },
      {
        name: "link_method",
        type: "select",
        options: "download,streaming",
        default: "download",
        required: false,
      },
      {
        name: "variant",
        type: "select",
        options: "quark,uc",
        default: "uc",
        required: false,
      },
    ],
    config: {
      name: "UCTV",
      local_sort: false,
      only_local: false,
      only_proxy: false,
      no_cache: false,
      no_upload: false,
      need_ms: false,
      default_root: "/",
    },
  },
}
